version: '3'
services:
  api:
    build: postgrest
    volumes:
    - ./postgrest/postgrest.conf:/etc/postgrest.conf
    ports:
    - 3002:3000
  db:
    image: postgres:10-beta3
    volumes:
    - ./postgresql/data:/var/lib/postgresql/data
    - ./postgresql/schema:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432
  adminer:
    image: adminer
    ports:
    - 8081:8080
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://localhost:3002/
    ports:
    - 8080:8080
